version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_APP_NAME:-zion_app}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
      - redis
    environment:
      - PHP_FPM_MAX_CHILDREN=${PHP_FPM_MAX_CHILDREN:-5}
      - PHP_FPM_START_SERVERS=${PHP_FPM_START_SERVERS:-2}
      - PHP_FPM_MIN_SPARE_SERVERS=${PHP_FPM_MIN_SPARE_SERVERS:-1}
      - PHP_FPM_MAX_SPARE_SERVERS=${PHP_FPM_MAX_SPARE_SERVERS:-3}

  webserver:
    image: nginx:alpine
    container_name: ${CONTAINER_WEBSERVER_NAME:-zion_webserver}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mariadb:${MARIADB_VERSION:-10.11}
    container_name: ${CONTAINER_DB_NAME:-zion_db}
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PHPMYADMIN_NAME:-zion_phpmyadmin}
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT:-3306}
      PMA_USER: ${DB_USERNAME:-laravel}
      PMA_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      UPLOAD_LIMIT: ${PHPMYADMIN_UPLOAD_LIMIT:-300M}
      MAX_EXECUTION_TIME: ${PHPMYADMIN_MAX_EXECUTION_TIME:-600}
    networks:
      - laravel
    depends_on:
      - db

  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    container_name: ${CONTAINER_REDIS_NAME:-zion_redis}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      sh -c "if [ -n \"$$REDIS_PASSWORD\" ]; then
        redis-server --requirepass \"$$REDIS_PASSWORD\" --appendonly yes;
      else
        redis-server --appendonly yes;
      fi"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redisdata:/data
    networks:
      - laravel
    healthcheck:
      test: >
        sh -c "if [ -n \"$$REDIS_PASSWORD\" ]; then
          redis-cli -a \"$$REDIS_PASSWORD\" ping;
        else
          redis-cli ping;
        fi"
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  laravel:
    driver: bridge
    name: ${NETWORK_NAME:-${COMPOSE_PROJECT_NAME:-laravel}_network}

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
